### ISSUE TITLE
Platonic Partners and Friendships

### ISSUE THREAD

**Issue by ellipszist** [ellipszist/StardewMods#198]
**[Platonic Partners and Friendships](https://www.nexusmods.com/stardewvalley/mods/8146)** Provides a config option to choose marriage candidates you want a platonic (i.e. non-romantic, non-dating) relationship with, and edits all their romantic 8+ heart dialogue and events to be consistent with a close friendship. Includes a detailed, customizable platonic partnership option as an alternative to marriage.

## Requested translations
 
* [x]  Abigail (แปลโดย @Hipster1707)
* [x]  Alex (แปลโดย @Fairy78)
* [x]  Elliot (แปลโดย @piyalucktm)
* [x]  Emily (แปลโดย @RushingOn)
* [x]  Haley (แปลโดย @wwwarmblanket)
* [x]  Harvey (แปลโดย @RushingOn)
* [x]  Leah (แปลโดย @MemoLiza)
* [x]  Maru (แปลโดย @Poopoo2002)
* [x]  Penny (แปลโดย @RushingOn)
* [x]  Sam (แปลโดย @RushingOn)
* [x]  Sebastian (แปลโดย @wwwarmblanket)
* [x]  Shane (แปลโดย @Poopoo2002)
* [x]  GenericTweaks (แปลโดย @RushingOn)
* [x]  Content (แปลโดย @RushingOn)

## Credit
**TODO**: I'll list translators in the Nexus credits. And probably the GitHub once I get around to making a readme for PPnF.

## See also
[source code](https://github.com/ellipszist/StardewMods/tree/master/[CP]%20Platonic%20Partners%20and%20Friendships)
